# cloudbuild.yaml
steps:
  # Build Discovery Server
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'discovery-server', '-am', '-DskipTests']
    id: 'build-discovery-server'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:latest',
      '-f', 'discovery-server/Dockerfile',
      'discovery-server'
    ]
    id: 'docker-build-discovery-server'
    waitFor: ['build-discovery-server']

  # Build API Gateway
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'api-gateway', '-am', '-DskipTests']
    id: 'build-api-gateway'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:latest',
      '-f', 'api-gateway/Dockerfile',
      'api-gateway'
    ]
    id: 'docker-build-api-gateway'
    waitFor: ['build-api-gateway']

  # Build Product Service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'product-service', '-am', '-DskipTests']
    id: 'build-product-service'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:latest',
      '-f', 'product-service/Dockerfile',
      'product-service'
    ]
    id: 'docker-build-product-service'
    waitFor: ['build-product-service']

  # Build Order Service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'order-service', '-am', '-DskipTests']
    id: 'build-order-service'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:latest',
      '-f', 'order-service/Dockerfile',
      'order-service'
    ]
    id: 'docker-build-order-service'
    waitFor: ['build-order-service']

  # Build Inventory Service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'inventory-service', '-am', '-DskipTests']
    id: 'build-inventory-service'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:latest',
      '-f', 'inventory-service/Dockerfile',
      'inventory-service'
    ]
    id: 'docker-build-inventory-service'
    waitFor: ['build-inventory-service']

  # Build Notification Service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'notification-service', '-am', '-DskipTests']
    id: 'build-notification-service'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:latest',
      '-f', 'notification-service/Dockerfile',
      'notification-service'
    ]
    id: 'docker-build-notification-service'
    waitFor: ['build-notification-service']

  # Push all images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server']
    waitFor: ['docker-build-discovery-server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway']
    waitFor: ['docker-build-api-gateway']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service']
    waitFor: ['docker-build-product-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service']
    waitFor: ['docker-build-order-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service']
    waitFor: ['docker-build-inventory-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service']
    waitFor: ['docker-build-notification-service']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'microservices-cluster'
      - '--zone=asia-southeast1-a'
    id: 'get-credentials'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'
    waitFor: ['get-credentials']

  # Update images in deployments
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/discovery-server'
      - 'discovery-server=asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/api-gateway'
      - 'api-gateway=asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/product-service'
      - 'product-service=asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/order-service'
      - 'order-service=asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/inventory-service'
      - 'inventory-service=asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/notification-service'
      - 'notification-service=asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=microservices-cluster'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:$SHORT_SHA'