# Add to existing cloudbuild.yaml

# Build Frontend
- name: 'node:18'
  id: 'build-frontend'
  dir: 'frontend'
  args: ['npm', 'ci']

- name: 'node:18'
  id: 'build-frontend-app'
  dir: 'frontend'
  args: ['npm', 'run', 'build']
  waitFor: ['build-frontend']

# Build Frontend Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-frontend'
  args: [
    'build',
    '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/frontend:$SHORT_SHA',
    '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/frontend:latest',
    'frontend'
  ]
  waitFor: ['build-frontend-app']

# Push Frontend Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-frontend'
  args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/frontend']
  waitFor: ['docker-frontend']

# Add to existing cloudbuild.yaml

# Build Frontend
- name: 'node:18'
  id: 'build-frontend'
  dir: 'frontend'
  args: ['npm', 'ci']

- name: 'node:18'
  id: 'build-frontend-app'
  dir: 'frontend'
  args: ['npm', 'run', 'build']
  waitFor: ['build-frontend']

# Build Frontend Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-frontend'
  args: [
    'build',
    '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/frontend:$SHORT_SHA',
    '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/frontend:latest',
    'frontend'
  ]
  waitFor: ['build-frontend-app']

# Push Frontend Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-frontend'
  args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/frontend']
  waitFor: ['docker-frontend']