# cloudbuild-argocd.yaml
steps:
  # Build all services
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'maven-build'
    args: ['clean', 'package', '-DskipTests', '-T', '1C']
    timeout: 1200s

  # Build và push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-discovery-server'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:latest',
      '-f', 'discovery-server/Dockerfile',
      'discovery-server'
    ]
    waitFor: ['maven-build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-gateway'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:latest',
      '-f', 'api-gateway/Dockerfile',
      'api-gateway'
    ]
    waitFor: ['maven-build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-product-service'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:latest',
      '-f', 'product-service/Dockerfile',
      'product-service'
    ]
    waitFor: ['maven-build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-order-service'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:latest',
      '-f', 'order-service/Dockerfile',
      'order-service'
    ]
    waitFor: ['maven-build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-inventory-service'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:latest',
      '-f', 'inventory-service/Dockerfile',
      'inventory-service'
    ]
    waitFor: ['maven-build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-notification-service'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:$SHORT_SHA',
      '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:latest',
      '-f', 'notification-service/Dockerfile',
      'notification-service'
    ]
    waitFor: ['maven-build']

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server']
    waitFor: ['build-discovery-server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway']
    waitFor: ['build-api-gateway']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service']
    waitFor: ['build-product-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service']
    waitFor: ['build-order-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service']
    waitFor: ['build-inventory-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service']
    waitFor: ['build-notification-service']

  # Update Kustomize images
  - name: 'gcr.io/cloud-builders/git'
    id: 'update-manifests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        # Configure git
        git config user.email "cloudbuild@gcp.com"
        git config user.name "Cloud Build"
        
        # Update kustomization with new image tags
        cd gitops/overlays/prod
        
        # Use kustomize to update images
        cat > kustomization.yaml << EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        
        namespace: microservices
        
        bases:
          - ../../base
        
        images:
          - name: discovery-server
            newName: asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server
            newTag: $SHORT_SHA
          - name: api-gateway
            newName: asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway
            newTag: $SHORT_SHA
          - name: product-service
            newName: asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service
            newTag: $SHORT_SHA
          - name: order-service
            newName: asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service
            newTag: $SHORT_SHA
          - name: inventory-service
            newName: asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service
            newTag: $SHORT_SHA
          - name: notification-service
            newName: asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service
            newTag: $SHORT_SHA
        EOF
        
        # Commit and push
        cd ../../..
        git add gitops/overlays/prod/kustomization.yaml
        git commit -m "Update image tags to $SHORT_SHA [skip ci]" || echo "No changes to commit"
        git push origin main

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/discovery-server:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/api-gateway:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/product-service:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/order-service:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/inventory-service:$SHORT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/microservices-repo/notification-service:$SHORT_SHA'